name: Tests

on:
  workflow_call:
    inputs:
      python_version:
        description: "Python version"
        type: string
        default: "3.12"
      packaging_with:
        description: "How to install packages (possible values: pip, poetry)"
        type: string
        default: "pip"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install dependencies (pip)
        if: ${{ inputs.packaging_with == "pip" }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Install dependencies (poetry)
        if: ${{ inputs.packaging_with == "poetry" }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.7.1
          poetry install

      - name: Testing
        run: pytest tests/
